import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'getting-started/index'},
      items: [
        'getting-started/overview',
        'getting-started/sign-in',
        'getting-started/basics',
        'getting-started/quickstart',
        'getting-started/no-code-best-practices',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guides/index'},
      items: [
        'guides/training',
        {
          type: 'category',
          label: 'Building Flows',
          link: {type: 'doc', id: 'guides/building-flows/index'},
          items: [
            'guides/building-flows/start-a-flow-from-a-template',
            'guides/building-flows/trigger-your-flow',
            'guides/building-flows/reach-out-to-services',
            'guides/building-flows/work-with-data',
            'guides/building-flows/run-a-nested-flow',
            'guides/building-flows/report-executions-by-email',
            'guides/building-flows/handy-tools',
            'guides/building-flows/use-ai-agent',
            'guides/building-flows/run-a-script',
            'guides/building-flows/aibuild',
            'guides/building-flows/aitask',
            'guides/building-flows/aiswarms',
            'guides/building-flows/mcp-client',
          ],
        },
        'guides/monitoring-executions',
        'guides/administrating-the-platform',
        'guides/airooms',
        'guides/import-a-flow',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {type: 'doc', id: 'integrations/index'},
      items: [
        'integrations/auth0',
        'integrations/atlassian',
        'integrations/aws',
        'integrations/bitwarden',
        'integrations/cisco-meraki',
        'integrations/crowdstrike',
        'integrations/elastic-cloud',
        'integrations/eset',
        'integrations/facebook',
        'integrations/google',
        'integrations/greynoise',
        'integrations/hashicorp-vault',
        'integrations/jamf-pro',
        'integrations/microsoft',
        'integrations/onelogin',
        'integrations/okta',
        'integrations/pagerduty',
        'integrations/phish-report',
        'integrations/salesforce',
        'integrations/semgrep',
        'integrations/sentinelone',
        'integrations/servicenow',
        'integrations/slack',
        'integrations/sophos',
        'integrations/urlscan',
        'integrations/virustotal',
        'integrations/wiz',
        'integrations/zabbix',
      ],
    },
    'support',
  ],
};

export default sidebars;
